### ISSUE TITLE
Archiving this repository

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/runall-extension#3]
This repository is part of the repositories listed as inactive during the [JupyterLab team call](https://github.com/jupyterlab/team-compass/issues/200).

This issue is to ping anyone listening for changes in this repository that starting from today if no volunteer propose him/herself to maintain this repository it will be archived in 2 weeks (aka July 27th, 2023).

**Comment by fcollonval** [comment]
Pinging main contributors for awareness: @sccolbert

**Comment by sccolbert** [comment]
I think this may have be @blink1073 being gracious in naming me the committer of this code. I don't think I was the one to actually write it.

**Comment by sccolbert** [comment]
I think this may have be @blink1073 being gracious in naming me the committer of this code. I don't think I was the one to actually write it.

**Comment by blink1073** [comment]
lol I have no recollection either way.  Archive away!
